### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1836]
I'm currently realizing that I need to spend way more times with other projects / my private live. At the same time, I want to prevent that this becomes an issue for the pypdf community.

One way to avoid issues is to automate the release process using Github Actions.

I was previously against doing so as I had security concerns / didn't see the advantage. Now I've learned that the PyPI access token can only be used to add new package versions, but not to add/remove owners or to delete the package.

This issue is meant as a point for discussion and a reminder for myself to do it.

## What I want to achieve

Having a way for trusted developers such as @Lucas-C to (a) release a new pypdf version himself or (b) allow somebody else (like @pubpub-zz / @MasterOdin) to release new versions in case I become inactive for a longer time.

At the same time, I don't want to lose control over the PyPI repository as it is of such critical importance.

## Tokens in GitHub

Github has 4 different types of tokens / secrets:

* Deploy keys
* Environment secrets
* Repository secrets: Used by pypdfium2 and https://github.com/PyFPDF/fpdf2
* Organization secrets

![image](https://user-images.githubusercontent.com/1658117/236675055-229b6c30-158a-4d50-8e88-53f71f121b39.png)

I think we want either environment or repository secrets, but I'm not quite sure which one.

I also don't know how we can prevent that a malicious Github Action would read/send the secret to an attacker. I guess we have to watch out that only trusted parties can get access to that secret.

## Triggering mechanism

How do other repositories trigger the release?

I think fpdf2 uses it was well.

I can see two potential mechanisms:

* Some UI
* Creation of a new tag with a certain tag pattern.

## Examples in the wild

* [pypdfium2](https://github.com/pypdfium2-team/pypdfium2/blob/main/.github/workflows/trigger_release.yaml): Trigger is a cron job that uses [`benc-uk/workflow-dispatch@v1`](https://github.com/benc-uk/workflow-dispatch) to run the [publish command](https://github.com/pypdfium2-team/pypdfium2/blob/main/.github/workflows/build_packages.yaml#L154-L213). That includes to publish (1) a Github release and (2) a PyPI release.
* [fpdf2](https://github.com/PyFPDF/fpdf2/blob/master/.github/workflows/continuous-integration-workflow.yml#L93-L105)
* [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/blob/main/.github/workflows/release.yml): Trigger is a new **git tag** push to the "main" repository.
* [pip-tools](https://github.com/jazzband/pip-tools/blob/main/.github/workflows/release.yml)

**Comment by MasterOdin** [comment]
Answering somewhat out of order:

> How do other repositories trigger the release?
> 
> I think fpdf2 uses it was well.

`fpdf2` has it setup in their singular workflow that any pushes to `master` will get published to PyPI if the current code version does not match any published version.

Alternative approaches are usually publishing on [pushing to a tag](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs) or [creating a GH release](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release). For the former, can then also hook that up to create a new release for you as well.

Could also use something like [semantic-release](https://github.com/semantic-release/semantic-release) to automate this, though I find repos that use it to release a bit too much.

> I think we want either environment or repository secrets, but I'm not quite sure which one.

If you can make use of the one of the protection rules for the environment (e.g. only allowed on certain branches), then environment is quite useful and adds some additional security. However, using regular repository secrets are also largely fine imo and if the latter has gotten breached, chances are the former would have as well, since:

> I also don't know how we can prevent that a malicious Github Action would read/send the secret to an attacker. I guess we have to watch out that only trusted parties can get access to that secret.

Secrets are only available to actions that are triggered from a commit within the repository. As such, any PR that is created against the repo will not have access to the secret, whether it's a repo secret or an environment secret. So long as you don't merge any malicious PRs or allow any malicious actors to be members of the org with write access, then the secrets are safe.

**Comment by Lucas-C** [comment]
> I think we want either environment or repository secrets, but I'm not quite sure which one.

On https://github.com/PyFPDF/fpdf2 we use a repository secret.

> fpdf2 has it setup in their singular workflow that any pushes to `master` will get published to PyPI if the current code version does not match any published version.

Exactly.

Overall I totally agree with @MasterOdin comment & analysis 😊

**Comment by Lucas-C** [comment]
Just a small extra note: currently the documentation page at <https://pypdf.readthedocs.io/en/latest/meta/project-governance.html#governance-leadership-and-steering-pypdf-forward> seems to imply that only the Benevolent Dictator can push new versions on Pypi. Maybe this should be updated to reflect that this is a responsability shared between them and the maintainers?

**Comment by mara004** [comment]
pypdfium2 has release automation as well. Our releases are scheduled, or can be manually triggered though GH Actions UI (or `gh` CLI). We use repository secrets.

**Comment by MartinThoma** [comment]
Thank you all for your input. I think I will go with a solution that is similar to what fpdf2 (@Lucas-C ) is doing. I hope I can implement that this weekend.

## Trigger Mechanisms

Choices I saw:

* **git tag push**: Used by [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar/blob/main/.github/workflows/release.yml) (jazzband)
* **new version push**: Used by [fpdf2](https://github.com/PyFPDF/fpdf2/blob/master/.github/workflows/continuous-integration-workflow.yml#L93-L105)
* **Creation of a GitHub Release**

I like the new version push as it is least prone to errors and most things can be automated. That especially means:

* **Consistency of Releases**: pypdf releases will look more alike every single time, because it's automated
* **Less Effort**: It's not that complicated, but still I'm currently happy if I can simplify things
* **Easier for new Maintainers**: If anybody takes over the maintainer-role for pypdf it will be easier for them.

## Automations

This is what should be done:

* Updating the CHANGELOG.md: Here I think I might need to be more strict about how I format PRs + enhance the current CHANGELOG creation script
* Creating a git tag: Very similar to the CHANGELOG
* Creating the Github Release Page: Very similar to the git tag + pinging people who contributed
* Publishing the PyPI package

**Comment by MasterOdin** [comment]
Let me know if you need any assistance for this @MartinThoma as I spend a lot of time working on these sorts of automation scripts / GH workflows.
