### ISSUE TITLE
Possibly undefined variable in FlateDecode.decode if parameters are an ArrayObject

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2159]
When looking through the code for understanding #2158, I stumbled upon some possibly undefined variable.

Let's take the following snippet: https://github.com/py-pdf/pypdf/blob/05f2a651917e1bd2fed6634efda6bb345b31de6b/pypdf/filters.py#L143-L165

It seems like in the first branch (lines 144 to 150), `colors` will never be defined, thus possibly leading to a crash at line 164 if I did not miss something. (I do not have any PDF file for this, as I just stumbled upon this by accident.)

**Comment by pubpub-zz** [comment]
Call me Dr Johns : I had to do archeology.🤣
This section of code is very old and actually obsolete. the call to the function actually uses only the dict version
This is confirmed by codecov.
Even useless I'm not incline to remove it.
if we leave it I propose to add comments+tag it this zone as obsolete in order to remove the section from coverage analysis
 @MartinThoma your opinion?

**Comment by stefan6419846** [comment]
I personally see no value if keeping it when this would fail anyway and (at least internally) is impossible to reach.

**Comment by pubpub-zz** [comment]
I did not though about it but we could raise an ObsoleteWarning and then remove it in a future version
