### ISSUE TITLE
Pypdf 4.2.0 requires dataclasses, which does not support python3.10 

### ISSUE THREAD

**Issue by Buvi1234** [py-pdf/pypdf#2650]
Hi,

I am trying to install pypdf version 4.2.0 in Python 3.10 environment. However, I've noticed that it requires the dataclass library. Upon inspecting the dataclass library, I found that it only works with Python version 3.6.

is there a way to install pypdf without the dataclass dependency to avoid these syntax issues?

reference: https://github.com/ericvsmith/dataclasses/blob/master/setup.py#L23

**Comment by stefan6419846** [comment]
This is wrong - our CI runs with Python up to version 3.12 without issues and there are enough *pypdf* installations out there which surely are not using Python 3.6 which is EOL for over two years now.

If you have a look at https://github.com/py-pdf/pypdf/blob/c227b0c725af6d0afc88bcf89348ece9b65adcb5/pyproject.toml#L33 you will see the the `dataclasses` backport is only required for Python < 3.7. Since Python 3.7, `dataclasses` is part of the stdlib and not required as external dependency any more.
